# Disable the broken python2.7 scripted input
[script://./bin/start_listener.py]
disabled = 1

# Monitors for actual data
[monitor:///private/var/log/system.log]
sourcetype = macos:system
index = main
disabled = 0

[monitor:///Applications/SplunkForwarder/var/log/splunk/splunkd.log]
sourcetype = splunkd
index = main
disabled = 0

[monitor://$SPLUNK_HOME/var/log/splunk/etairos_tee.log]
sourcetype = etairos:tee:log
index = _internal
disabled = 0
